SELECT
	Final.DatePart AS DatePart,
	Final.Cal_Date AS Cal_Date,
	SUM(Final.HAL_OB_FG_AB) AS HAL_OB_FG_AB,
	SUM(Final.HL_FG_AB) AS HL_FG_AB,
	SUM(Final.HAL_OB_FG_AB) + SUM(Final.HL_FG_AB) AS HAL_FG_AB_TOT,
	SUM(Final.HAL_OB_MR_AB) AS HAL_OB_MR_AB,
	SUM(Final.HL_MR) AS HL_MR,
	SUM(Final.HAL_OB_MR_AB) + SUM(Final.HL_MR) AS HAL_MR_AB_TOT,
	SUM(Final.HAL_OB_DOC_AB) AS HAL_OB_DOC_AB,
	SUM(Final.HL_DOC) AS HL_DOC,
	SUM(Final.HAL_OB_DOC_AB) + SUM(Final.HL_DOC) AS H_HAL_DOC_AB_TOT,
	SUM(Final.HAL_OB_POSM_AB) AS HAL_OB_POSM_AB,
	SUM(Final.HL_POSM) AS HL_POSM,
	SUM(Final.HAL_OB_POSM_AB) + SUM(Final.HL_POSM) AS HAL_POSM_AB_TOT,
	SUM(Final.HAL_OB_FG_TC) AS HAL_OB_FG_TC, --temp controll
	SUM(Final.HL_FG) AS HL_FG, --temp controll storage
	SUM(Final.HAL_OB_FG_TC) + SUM(Final.HL_FG) AS HAL_FG_TC_TOT, --temp controll tot
	SUM(Final.HAL_OB_FG_AB) + SUM(Final.HL_FG_AB) + SUM(Final.HAL_OB_MR_AB) + SUM(Final.HL_MR) + SUM(Final.HAL_OB_DOC_AB) + SUM(Final.HL_DOC) + SUM(Final.HAL_OB_POSM_AB) + SUM(Final.HL_POSM) AS HAL_AB_TOT
	
FROM
(
	-----------------------------------------------------------------------------------------------------------------------
	SELECT
		FORMAT(CAST(DATEADD(minute, 30, DATEADD(hour, 5, c.CHARGE_DATE)) AS DATE), 'MM-yyyy') AS DatePart,
		CAST(DATEADD(minute, 30, DATEADD(hour, 5, c.CHARGE_DATE)) AS DATE) AS Cal_Date,
		SUM(c.CHARGE_QTY) AS HAL_OB_FG_AB,
		0 AS HL_FG_AB,
		0 AS HAL_OB_MR_AB,
		0 AS HL_MR,
		0 AS HAL_OB_DOC_AB,
		0 AS HL_DOC,
		0 AS HAL_OB_POSM_AB,
		0 AS HL_POSM,
		0 AS HAL_OB_FG_TC,
		0 AS HL_FG
		
	FROM BILLADMIN.BIC_CHARGE_CODE CHG_CODE
	LEFT JOIN BILLADMIN.BIC_CHARGE c ON CHG_CODE.CHARGE_CODE = c.CHARGE_CODE
	WHERE c.CHARGE_CODE = 'HAL-OB-FG-AB'	
	GROUP BY CAST(DATEADD(minute, 30, DATEADD(hour, 5, c.CHARGE_DATE)) AS DATE)

	UNION ALL

	SELECT
		FORMAT(CAST(DATEADD(minute, 30, DATEADD(hour, 5, c.CHARGE_DATE)) AS DATE), 'MM-yyyy') AS DatePart,
		CAST(DATEADD(minute, 30, DATEADD(hour, 5, c.CHARGE_DATE)) AS DATE) AS Cal_Date,
		0 AS HAL_OB_FG_AB,
		SUM(c.CHARGE_QTY) AS HL_FG_AB,
		0 AS HAL_OB_MR_AB,
		0 AS HL_MR,
		0 AS HAL_OB_DOC_AB,
		0 AS HL_DOC,
		0 AS HAL_OB_POSM_AB,
		0 AS HL_POSM,
		0 AS HAL_OB_FG_TC,
		0 AS HL_FG
		
	FROM BILLADMIN.BIC_CHARGE_CODE CHG_CODE
	LEFT JOIN BILLADMIN.BIC_CHARGE c ON CHG_CODE.CHARGE_CODE = c.CHARGE_CODE
	WHERE c.CHARGE_CODE = 'HL-ST' AND c.ITEM_GROUP = 'HL-FG-AB'
	GROUP BY CAST(DATEADD(minute, 30, DATEADD(hour, 5, c.CHARGE_DATE)) AS DATE)
	-----------------------------------------------------------------------------------------------------------------------
	UNION ALL
	
	SELECT
		FORMAT(CAST(DATEADD(minute, 30, DATEADD(hour, 5, c.CHARGE_DATE)) AS DATE), 'MM-yyyy') AS DatePart,
		CAST(DATEADD(minute, 30, DATEADD(hour, 5, c.CHARGE_DATE)) AS DATE) AS Cal_Date,
		0 AS HAL_OB_FG_AB,
		0 AS HL_FG_AB,
		SUM(c.CHARGE_QTY) AS HAL_OB_MR_AB,
		0 AS HL_MR,
		0 AS HAL_OB_DOC_AB,
		0 AS HL_DOC,
		0 AS HAL_OB_POSM_AB,
		0 AS HL_POSM,
		0 AS HAL_OB_FG_TC,
		0 AS HL_FG

	FROM BILLADMIN.BIC_CHARGE_CODE CHG_CODE
	LEFT JOIN BILLADMIN.BIC_CHARGE c ON CHG_CODE.CHARGE_CODE = c.CHARGE_CODE
	WHERE c.CHARGE_CODE = 'HAL-OB-MR-AB'	
	GROUP BY CAST(DATEADD(minute, 30, DATEADD(hour, 5, c.CHARGE_DATE)) AS DATE)

	UNION ALL

	SELECT
		FORMAT(CAST(DATEADD(minute, 30, DATEADD(hour, 5, c.CHARGE_DATE)) AS DATE), 'MM-yyyy') AS DatePart,
		CAST(DATEADD(minute, 30, DATEADD(hour, 5, c.CHARGE_DATE)) AS DATE) AS Cal_Date,
		0 AS HAL_OB_FG_AB,
		0 AS HL_FG_AB,
		0 AS HAL_OB_MR_AB,
		SUM(c.CHARGE_QTY) AS HL_MR,
		0 AS HAL_OB_DOC_AB,
		0 AS HL_DOC,
		0 AS HAL_OB_POSM_AB,
		0 AS HL_POSM,
		0 AS HAL_OB_FG_TC,
		0 AS HL_FG
		
	FROM BILLADMIN.BIC_CHARGE_CODE CHG_CODE
	LEFT JOIN BILLADMIN.BIC_CHARGE c ON CHG_CODE.CHARGE_CODE = c.CHARGE_CODE
	WHERE c.CHARGE_CODE = 'HL-ST' AND c.ITEM_GROUP = 'HL-MR'
	GROUP BY CAST(DATEADD(minute, 30, DATEADD(hour, 5, c.CHARGE_DATE)) AS DATE)
	-----------------------------------------------------------------------------------------------------------------------
	UNION ALL
	
	SELECT
		FORMAT(CAST(DATEADD(minute, 30, DATEADD(hour, 5, c.CHARGE_DATE)) AS DATE), 'MM-yyyy') AS DatePart,
		CAST(DATEADD(minute, 30, DATEADD(hour, 5, c.CHARGE_DATE)) AS DATE) AS Cal_Date,
		0 AS HAL_OB_FG_AB,
		0 AS HL_FG_AB,
		0 AS HAL_OB_MR_AB,
		0 AS HL_MR,
		SUM(c.CHARGE_QTY) AS HAL_OB_DOC_AB,
		0 AS HL_DOC,
		0 AS HAL_OB_POSM_AB,
		0 AS HL_POSM,
		0 AS HAL_OB_FG_TC,
		0 AS HL_FG

	FROM BILLADMIN.BIC_CHARGE_CODE CHG_CODE
	LEFT JOIN BILLADMIN.BIC_CHARGE c ON CHG_CODE.CHARGE_CODE = c.CHARGE_CODE
	WHERE c.CHARGE_CODE = 'HAL-OB-DOC-AB'	
	GROUP BY CAST(DATEADD(minute, 30, DATEADD(hour, 5, c.CHARGE_DATE)) AS DATE)

	UNION ALL

	SELECT
		FORMAT(CAST(DATEADD(minute, 30, DATEADD(hour, 5, c.CHARGE_DATE)) AS DATE), 'MM-yyyy') AS DatePart,
		CAST(DATEADD(minute, 30, DATEADD(hour, 5, c.CHARGE_DATE)) AS DATE) AS Cal_Date,
		0 AS HAL_OB_FG_AB,
		0 AS HL_FG_AB,
		0 AS HAL_OB_MR_AB,
		0 AS HL_MR,
		0 AS HAL_OB_DOC_AB,
		SUM(c.CHARGE_QTY) AS HL_DOC,
		0 AS HAL_OB_POSM_AB,
		0 AS HL_POSM,
		0 AS HAL_OB_FG_TC,
		0 AS HL_FG
		
	FROM BILLADMIN.BIC_CHARGE_CODE CHG_CODE
	LEFT JOIN BILLADMIN.BIC_CHARGE c ON CHG_CODE.CHARGE_CODE = c.CHARGE_CODE
	WHERE c.CHARGE_CODE = 'HL-ST' AND c.ITEM_GROUP = 'HL-DOC'
	GROUP BY CAST(DATEADD(minute, 30, DATEADD(hour, 5, c.CHARGE_DATE)) AS DATE)
	-----------------------------------------------------------------------------------------------------------------------
	UNION ALL
	
	SELECT
		FORMAT(CAST(DATEADD(minute, 30, DATEADD(hour, 5, c.CHARGE_DATE)) AS DATE), 'MM-yyyy') AS DatePart,
		CAST(DATEADD(minute, 30, DATEADD(hour, 5, c.CHARGE_DATE)) AS DATE) AS Cal_Date,
		0 AS HAL_OB_FG_AB,
		0 AS HL_FG_AB,
		0 AS HAL_OB_MR_AB,
		0 AS HL_MR,
		0 AS HAL_OB_DOC_AB,
		0 AS HL_DOC,
		SUM(c.CHARGE_QTY) AS HAL_OB_POSM_AB,
		0 AS HL_POSM,
		0 AS HAL_OB_FG_TC,
		0 AS HL_FG

	FROM BILLADMIN.BIC_CHARGE_CODE CHG_CODE
	LEFT JOIN BILLADMIN.BIC_CHARGE c ON CHG_CODE.CHARGE_CODE = c.CHARGE_CODE
	WHERE c.CHARGE_CODE = 'HAL-OB-POSM-AB'	
	GROUP BY CAST(DATEADD(minute, 30, DATEADD(hour, 5, c.CHARGE_DATE)) AS DATE)

	UNION ALL

	SELECT
		FORMAT(CAST(DATEADD(minute, 30, DATEADD(hour, 5, c.CHARGE_DATE)) AS DATE), 'MM-yyyy') AS DatePart,
		CAST(DATEADD(minute, 30, DATEADD(hour, 5, c.CHARGE_DATE)) AS DATE) AS Cal_Date,
		0 AS HAL_OB_FG_AB,
		0 AS HL_FG_AB,
		0 AS HAL_OB_MR_AB,
		0 AS HL_MR,
		0 AS HAL_OB_DOC_AB,
		0 AS HL_DOC,
		0 AS HAL_OB_POSM_AB,
		SUM(c.CHARGE_QTY) AS HL_POSM,
		0 AS HAL_OB_FG_TC,
		0 AS HL_FG
		
	FROM BILLADMIN.BIC_CHARGE_CODE CHG_CODE
	LEFT JOIN BILLADMIN.BIC_CHARGE c ON CHG_CODE.CHARGE_CODE = c.CHARGE_CODE
	WHERE c.CHARGE_CODE = 'HL-ST' AND c.ITEM_GROUP = 'HL-POSM'
	GROUP BY CAST(DATEADD(minute, 30, DATEADD(hour, 5, c.CHARGE_DATE)) AS DATE)
	-----------------------------------------------------------------------------------------------------------------------
	UNION ALL
	
	SELECT
		FORMAT(CAST(DATEADD(minute, 30, DATEADD(hour, 5, c.CHARGE_DATE)) AS DATE), 'MM-yyyy') AS DatePart,
		CAST(DATEADD(minute, 30, DATEADD(hour, 5, c.CHARGE_DATE)) AS DATE) AS Cal_Date,
		0 AS HAL_OB_FG_AB,
		0 AS HL_FG_AB,
		0 AS HAL_OB_MR_AB,
		0 AS HL_MR,
		0 AS HAL_OB_DOC_AB,
		0 AS HL_DOC,
		0 AS HAL_OB_POSM_AB,
		0 AS HL_POSM,
		SUM(c.CHARGE_QTY) AS HAL_OB_FG_TC,
		0 AS HL_FG

	FROM BILLADMIN.BIC_CHARGE_CODE CHG_CODE
	LEFT JOIN BILLADMIN.BIC_CHARGE c ON CHG_CODE.CHARGE_CODE = c.CHARGE_CODE
	WHERE c.CHARGE_CODE = 'HAL-OB-FG-TC'	
	GROUP BY CAST(DATEADD(minute, 30, DATEADD(hour, 5, c.CHARGE_DATE)) AS DATE)

	UNION ALL

	SELECT
		FORMAT(CAST(DATEADD(minute, 30, DATEADD(hour, 5, c.CHARGE_DATE)) AS DATE), 'MM-yyyy') AS DatePart,
		CAST(DATEADD(minute, 30, DATEADD(hour, 5, c.CHARGE_DATE)) AS DATE) AS Cal_Date,
		0 AS HAL_OB_FG_AB,
		0 AS HL_FG_AB,
		0 AS HAL_OB_MR_AB,
		0 AS HL_MR,
		0 AS HAL_OB_DOC_AB,
		0 AS HL_DOC,
		0 AS HAL_OB_POSM_AB,
		0 AS HL_POSM,
		0 AS HAL_OB_FG_TC,
		SUM(c.CHARGE_QTY) AS HL_FG
		
	FROM BILLADMIN.BIC_CHARGE_CODE CHG_CODE
	LEFT JOIN BILLADMIN.BIC_CHARGE c ON CHG_CODE.CHARGE_CODE = c.CHARGE_CODE
	WHERE c.CHARGE_CODE = 'HL-ST' AND c.ITEM_GROUP = 'HL-FG-TC'
	GROUP BY CAST(DATEADD(minute, 30, DATEADD(hour, 5, c.CHARGE_DATE)) AS DATE)
	-----------------------------------------------------------------------------------------------------------------------
)Final
GROUP BY
	Final.DatePart,
    Final.Cal_Date
