SELECT Outound.DatePart,
	Outound.Cal_Date,
	Outound.HAL_OB_FG_AB,
	Outound.HAL_OB_FG_TC,
	Outound.HAL_OB_MR_AB,
	Outound.HAL_OB_POSM_AB,
	Outound.HAL_OB_SR_AB,
	Outound.HAL_OB_SR_TC,
	Outound.HAL_OB_DOC_AB
FROM (
	SELECT FORMAT(CAST(DATEADD(minute, 30, DATEADD(hour, 5, c.CHARGE_DATE)) AS DATE), 'MM-yyyy') AS DatePart,
		CAST(DATEADD(minute, 30, DATEADD(hour, 5, c.CHARGE_DATE)) AS DATE) AS Cal_Date,
		SUM(c.CHARGE_QTY) AS HAL_OB_FG_AB,
		0 AS HAL_OB_FG_TC,
		0 AS HAL_OB_MR_AB,
		0 AS HAL_OB_POSM_AB,
		0 AS HAL_OB_SR_AB,
		0 AS HAL_OB_SR_TC,
		0 AS HAL_OB_DOC_AB
	FROM BILLADMIN.BIC_CHARGE_CODE CHG_CODE
	LEFT JOIN BILLADMIN.BIC_CHARGE c ON CHG_CODE.CHARGE_CODE = c.CHARGE_CODE
	WHERE c.CHARGE_CODE = 'HAL-OB-FG-AB'
	GROUP BY CAST(DATEADD(minute, 30, DATEADD(hour, 5, c.CHARGE_DATE)) AS DATE)
	
	UNION ALL
	
	SELECT FORMAT(CAST(DATEADD(minute, 30, DATEADD(hour, 5, c.CHARGE_DATE)) AS DATE), 'MM-yyyy') AS DatePart,
		CAST(DATEADD(minute, 30, DATEADD(hour, 5, c.CHARGE_DATE)) AS DATE) AS Cal_Date,
		0 AS HAL_OB_FG_AB,
		SUM(c.CHARGE_QTY) AS HAL_OB_FG_TC,
		0 AS HAL_OB_MR_AB,
		0 AS HAL_OB_POSM_AB,
		0 AS HAL_OB_SR_AB,
		0 AS HAL_OB_SR_TC,
		0 AS HAL_OB_DOC_AB
	FROM BILLADMIN.BIC_CHARGE_CODE CHG_CODE
	LEFT JOIN BILLADMIN.BIC_CHARGE c ON CHG_CODE.CHARGE_CODE = c.CHARGE_CODE
	WHERE c.CHARGE_CODE = 'HAL-OB-FG-TC'
	GROUP BY CAST(DATEADD(minute, 30, DATEADD(hour, 5, c.CHARGE_DATE)) AS DATE)
	
	UNION ALL
	
	SELECT FORMAT(CAST(DATEADD(minute, 30, DATEADD(hour, 5, c.CHARGE_DATE)) AS DATE), 'MM-yyyy') AS DatePart,
		CAST(DATEADD(minute, 30, DATEADD(hour, 5, c.CHARGE_DATE)) AS DATE) AS Cal_Date,
		0 AS HAL_OB_FG_AB,
		0 AS HAL_OB_FG_TC,
		SUM(c.CHARGE_QTY) AS HAL_OB_MR_AB,
		0 AS HAL_OB_POSM_AB,
		0 AS HAL_OB_SR_AB,
		0 AS HAL_OB_SR_TC,
		0 AS HAL_OB_DOC_AB
	FROM BILLADMIN.BIC_CHARGE_CODE CHG_CODE
	LEFT JOIN BILLADMIN.BIC_CHARGE c ON CHG_CODE.CHARGE_CODE = c.CHARGE_CODE
	WHERE c.CHARGE_CODE = 'HAL-OB-MR-AB'
	GROUP BY CAST(DATEADD(minute, 30, DATEADD(hour, 5, c.CHARGE_DATE)) AS DATE)
	
	UNION ALL
	
	SELECT FORMAT(CAST(DATEADD(minute, 30, DATEADD(hour, 5, c.CHARGE_DATE)) AS DATE), 'MM-yyyy') AS DatePart,
		CAST(DATEADD(minute, 30, DATEADD(hour, 5, c.CHARGE_DATE)) AS DATE) AS Cal_Date,
		0 AS HAL_OB_FG_AB,
		0 AS HAL_OB_FG_TC,
		0 AS HAL_OB_MR_AB,
		SUM(c.CHARGE_QTY) AS HAL_OB_POSM_AB,
		0 AS HAL_OB_SR_AB,
		0 AS HAL_OB_SR_TC,
		0 AS HAL_OB_DOC_AB
	FROM BILLADMIN.BIC_CHARGE_CODE CHG_CODE
	LEFT JOIN BILLADMIN.BIC_CHARGE c ON CHG_CODE.CHARGE_CODE = c.CHARGE_CODE
	WHERE c.CHARGE_CODE = 'HAL-OB-POSM-AB'
	GROUP BY CAST(DATEADD(minute, 30, DATEADD(hour, 5, c.CHARGE_DATE)) AS DATE)
	
	UNION ALL
	
	SELECT FORMAT(CAST(DATEADD(minute, 30, DATEADD(hour, 5, c.CHARGE_DATE)) AS DATE), 'MM-yyyy') AS DatePart,
		CAST(DATEADD(minute, 30, DATEADD(hour, 5, c.CHARGE_DATE)) AS DATE) AS Cal_Date,
		0 AS HAL_OB_FG_AB,
		0 AS HAL_OB_FG_TC,
		0 AS HAL_OB_MR_AB,
		0 AS HAL_OB_POSM_AB,
		SUM(c.CHARGE_QTY) AS HAL_OB_SR_AB,
		0 AS HAL_OB_SR_TC,
		0 AS HAL_OB_DOC_AB
	FROM BILLADMIN.BIC_CHARGE_CODE CHG_CODE
	LEFT JOIN BILLADMIN.BIC_CHARGE c ON CHG_CODE.CHARGE_CODE = c.CHARGE_CODE
	WHERE c.CHARGE_CODE = 'HAL-OB-SR-AB'
	GROUP BY CAST(DATEADD(minute, 30, DATEADD(hour, 5, c.CHARGE_DATE)) AS DATE)
	
	UNION ALL
	
	SELECT FORMAT(CAST(DATEADD(minute, 30, DATEADD(hour, 5, c.CHARGE_DATE)) AS DATE), 'MM-yyyy') AS DatePart,
		CAST(DATEADD(minute, 30, DATEADD(hour, 5, c.CHARGE_DATE)) AS DATE) AS Cal_Date,
		0 AS HAL_OB_FG_AB,
		0 AS HAL_OB_FG_TC,
		0 AS HAL_OB_MR_AB,
		0 AS HAL_OB_POSM_AB,
		0 AS HAL_OB_SR_AB,
		SUM(c.CHARGE_QTY) AS HAL_OB_SR_TC,
		0 AS HAL_OB_DOC_AB
	FROM BILLADMIN.BIC_CHARGE_CODE CHG_CODE
	LEFT JOIN BILLADMIN.BIC_CHARGE c ON CHG_CODE.CHARGE_CODE = c.CHARGE_CODE
	WHERE c.CHARGE_CODE = 'HAL-OB-SR-TC'
	GROUP BY CAST(DATEADD(minute, 30, DATEADD(hour, 5, c.CHARGE_DATE)) AS DATE)
	
	UNION ALL
	
	SELECT FORMAT(CAST(DATEADD(minute, 30, DATEADD(hour, 5, c.CHARGE_DATE)) AS DATE), 'MM-yyyy') AS DatePart,
		CAST(DATEADD(minute, 30, DATEADD(hour, 5, c.CHARGE_DATE)) AS DATE) AS Cal_Date,
		0 AS HAL_OB_FG_AB,
		0 AS HAL_OB_FG_TC,
		0 AS HAL_OB_MR_AB,
		0 AS HAL_OB_POSM_AB,
		0 AS HAL_OB_SR_AB,
		0 AS HAL_OB_SR_TC,
		SUM(c.CHARGE_QTY) AS HAL_OB_DOC_AB
	FROM BILLADMIN.BIC_CHARGE_CODE CHG_CODE
	LEFT JOIN BILLADMIN.BIC_CHARGE c ON CHG_CODE.CHARGE_CODE = c.CHARGE_CODE
	WHERE c.CHARGE_CODE = 'HAL-OB-DOC-AB'
	GROUP BY CAST(DATEADD(minute, 30, DATEADD(hour, 5, c.CHARGE_DATE)) AS DATE)
	) Outound
