SELECT
	Summary.DatePart AS DatePart ,
	SUM(Summary.HAL_IB_FG_AB) AS HAL_IB_FG_AB,
	SUM(Summary.HAL_IB_FG_TC) AS HAL_IB_FG_TC,
	SUM(Summary.HAL_IB_MR_AB) AS HAL_IB_MR_AB,
	SUM(Summary.HAL_IB_POSM_AB) AS HAL_IB_POSM_AB,
	SUM(Summary.HAL_IB_DOC_AB) AS HAL_IB_DOC_AB,
	SUM(Summary.HAL_OB_FG_AB) AS HAL_OB_FG_AB,
	SUM(Summary.HAL_OB_FG_TC) AS HAL_OB_FG_TC,
	SUM(Summary.HAL_OB_MR_AB) AS HAL_OB_MR_AB,
	SUM(Summary.HAL_OB_POSM_AB) AS HAL_OB_POSM_AB,
	SUM(Summary.HAL_OB_DOC_AB) AS HAL_OB_DOC_AB,
	SUM(Summary.HAL_AB_TOT) AS HAL_AB_TOT,
	SUM(Summary.Extra_AB) AS Extra_AB,
	SUM(Summary.HAL_FG_TC_TOT) AS HAL_FG_TC_TOT,
	SUM(Summary.Extra_TC) AS Extra_TC

FROM
(
	--Inbound
	SELECT
		FORMAT(CAST(DATEADD(minute, 30, DATEADD(hour, 5, c.CHARGE_DATE)) AS DATE), 'MM-yyyy') AS DatePart,
		SUM(c.CHARGE_QTY) AS HAL_IB_FG_AB,
		0 AS HAL_IB_FG_TC,
		0 AS HAL_IB_MR_AB,
		0 AS HAL_IB_POSM_AB,
		0 AS HAL_IB_DOC_AB,
		0 AS HAL_OB_FG_AB,
		0 AS HAL_OB_FG_TC,
		0 AS HAL_OB_MR_AB,
		0 AS HAL_OB_POSM_AB,
		0 AS HAL_OB_DOC_AB,
		0 AS HAL_AB_TOT,
		0 AS Extra_AB,
		0 AS HAL_FG_TC_TOT,
		0 AS Extra_TC

	FROM BILLADMIN.BIC_CHARGE_CODE CHG_CODE
	LEFT JOIN BILLADMIN.BIC_CHARGE c ON CHG_CODE.CHARGE_CODE = c.CHARGE_CODE
	WHERE c.CHARGE_CODE = 'HAL-IB-FG-AB'
	GROUP BY FORMAT(CAST(DATEADD(minute, 30, DATEADD(hour, 5, c.CHARGE_DATE)) AS DATE), 'MM-yyyy')

	UNION ALL

	SELECT FORMAT(CAST(DATEADD(minute, 30, DATEADD(hour, 5, c.CHARGE_DATE)) AS DATE), 'MM-yyyy') AS DatePart,
		0 AS HAL_IB_FG_AB,
		SUM(c.CHARGE_QTY) AS HAL_IB_FG_TC,
		0 AS HAL_IB_MR_AB,
		0 AS HAL_IB_POSM_AB,
		0 AS HAL_IB_DOC_AB,
		0 AS HAL_OB_FG_AB,
		0 AS HAL_OB_FG_TC,
		0 AS HAL_OB_MR_AB,
		0 AS HAL_OB_POSM_AB,
		0 AS HAL_OB_DOC_AB,
		0 AS HAL_AB_TOT,
		0 AS Extra_AB,
		0 AS HAL_FG_TC_TOT,
		0 AS Extra_TC
		
	FROM BILLADMIN.BIC_CHARGE_CODE CHG_CODE
	LEFT JOIN BILLADMIN.BIC_CHARGE c ON CHG_CODE.CHARGE_CODE = c.CHARGE_CODE
	WHERE c.CHARGE_CODE = 'HAL-IB-FG-TC'
	GROUP BY FORMAT(CAST(DATEADD(minute, 30, DATEADD(hour, 5, c.CHARGE_DATE)) AS DATE), 'MM-yyyy')

	UNION ALL

	SELECT FORMAT(CAST(DATEADD(minute, 30, DATEADD(hour, 5, c.CHARGE_DATE)) AS DATE), 'MM-yyyy') AS DatePart,
		0 AS HAL_IB_FG_AB,
		0 AS HAL_IB_FG_TC,
		SUM(c.CHARGE_QTY) AS HAL_IB_MR_AB,
		0 AS HAL_IB_POSM_AB,
		0 AS HAL_IB_DOC_AB,
		0 AS HAL_OB_FG_AB,
		0 AS HAL_OB_FG_TC,
		0 AS HAL_OB_MR_AB,
		0 AS HAL_OB_POSM_AB,
		0 AS HAL_OB_DOC_AB,
		0 AS HAL_AB_TOT,
		0 AS Extra_AB,
		0 AS HAL_FG_TC_TOT,
		0 AS Extra_TC
		
	FROM BILLADMIN.BIC_CHARGE_CODE CHG_CODE
	LEFT JOIN BILLADMIN.BIC_CHARGE c ON CHG_CODE.CHARGE_CODE = c.CHARGE_CODE
	WHERE c.CHARGE_CODE = 'HAL-IB-MR-AB'
	GROUP BY FORMAT(CAST(DATEADD(minute, 30, DATEADD(hour, 5, c.CHARGE_DATE)) AS DATE), 'MM-yyyy')

	UNION ALL

	SELECT FORMAT(CAST(DATEADD(minute, 30, DATEADD(hour, 5, c.CHARGE_DATE)) AS DATE), 'MM-yyyy') AS DatePart,	
		0 AS HAL_IB_FG_AB,
		0 AS HAL_IB_FG_TC,
		0 AS HAL_IB_MR_AB,
		SUM(c.CHARGE_QTY) AS HAL_IB_POSM_AB,
		0 AS HAL_IB_DOC_AB,
		0 AS HAL_OB_FG_AB,
		0 AS HAL_OB_FG_TC,
		0 AS HAL_OB_MR_AB,
		0 AS HAL_OB_POSM_AB,
		0 AS HAL_OB_DOC_AB,
		0 AS HAL_AB_TOT,
		0 AS Extra_AB,
		0 AS HAL_FG_TC_TOT,
		0 AS Extra_TC
		
	FROM BILLADMIN.BIC_CHARGE_CODE CHG_CODE
	LEFT JOIN BILLADMIN.BIC_CHARGE c ON CHG_CODE.CHARGE_CODE = c.CHARGE_CODE
	WHERE c.CHARGE_CODE = 'HAL-IB-POSM-AB'
	GROUP BY FORMAT(CAST(DATEADD(minute, 30, DATEADD(hour, 5, c.CHARGE_DATE)) AS DATE), 'MM-yyyy')

	UNION ALL

	SELECT FORMAT(CAST(DATEADD(minute, 30, DATEADD(hour, 5, c.CHARGE_DATE)) AS DATE), 'MM-yyyy') AS DatePart,
		0 AS HAL_IB_FG_AB,
		0 AS HAL_IB_FG_TC,
		0 AS HAL_IB_MR_AB,
		0 AS HAL_IB_POSM_AB,
		SUM(c.CHARGE_QTY) AS HAL_IB_DOC_AB,
		0 AS HAL_OB_FG_AB,
		0 AS HAL_OB_FG_TC,
		0 AS HAL_OB_MR_AB,
		0 AS HAL_OB_POSM_AB,
		0 AS HAL_OB_DOC_AB,
		0 AS HAL_AB_TOT,
		0 AS Extra_AB,
		0 AS HAL_FG_TC_TOT,
		0 AS Extra_TC		
		
	FROM BILLADMIN.BIC_CHARGE_CODE CHG_CODE
	LEFT JOIN BILLADMIN.BIC_CHARGE c ON CHG_CODE.CHARGE_CODE = c.CHARGE_CODE
	WHERE c.CHARGE_CODE = 'HAL-IB-DOC-AB'
	GROUP BY FORMAT(CAST(DATEADD(minute, 30, DATEADD(hour, 5, c.CHARGE_DATE)) AS DATE), 'MM-yyyy')
	
	UNION ALL
	
	--Outbound
	SELECT FORMAT(CAST(DATEADD(minute, 30, DATEADD(hour, 5, c.CHARGE_DATE)) AS DATE), 'MM-yyyy') AS DatePart,
		0 AS HAL_IB_FG_AB,
		0 AS HAL_IB_FG_TC,
		0 AS HAL_IB_MR_AB,
		0 AS HAL_IB_POSM_AB,
		0 AS HAL_IB_DOC_AB,
		SUM(c.CHARGE_QTY) AS HAL_OB_FG_AB,
		0 AS HAL_OB_FG_TC,
		0 AS HAL_OB_MR_AB,
		0 AS HAL_OB_POSM_AB,
		0 AS HAL_OB_DOC_AB,
		0 AS HAL_AB_TOT,
		0 AS Extra_AB,
		0 AS HAL_FG_TC_TOT,
		0 AS Extra_TC		
		
	FROM BILLADMIN.BIC_CHARGE_CODE CHG_CODE
	LEFT JOIN BILLADMIN.BIC_CHARGE c ON CHG_CODE.CHARGE_CODE = c.CHARGE_CODE
	WHERE c.CHARGE_CODE = 'HAL-OB-FG-AB'
	GROUP BY FORMAT(CAST(DATEADD(minute, 30, DATEADD(hour, 5, c.CHARGE_DATE)) AS DATE), 'MM-yyyy')
	
	UNION ALL
	
	SELECT FORMAT(CAST(DATEADD(minute, 30, DATEADD(hour, 5, c.CHARGE_DATE)) AS DATE), 'MM-yyyy') AS DatePart,
		0 AS HAL_IB_FG_AB,
		0 AS HAL_IB_FG_TC,
		0 AS HAL_IB_MR_AB,
		0 AS HAL_IB_POSM_AB,
		0 AS HAL_IB_DOC_AB,
		0 AS HAL_OB_FG_AB,
		SUM(c.CHARGE_QTY) AS HAL_OB_FG_TC,
		0 AS HAL_OB_MR_AB,
		0 AS HAL_OB_POSM_AB,
		0 AS HAL_OB_DOC_AB,
		0 AS HAL_AB_TOT,
		0 AS Extra_AB,
		0 AS HAL_FG_TC_TOT,
		0 AS Extra_TC		
		
	FROM BILLADMIN.BIC_CHARGE_CODE CHG_CODE
	LEFT JOIN BILLADMIN.BIC_CHARGE c ON CHG_CODE.CHARGE_CODE = c.CHARGE_CODE
	WHERE c.CHARGE_CODE = 'HAL-OB-FG-TC'
	GROUP BY FORMAT(CAST(DATEADD(minute, 30, DATEADD(hour, 5, c.CHARGE_DATE)) AS DATE), 'MM-yyyy')
	
	UNION ALL
	
	SELECT FORMAT(CAST(DATEADD(minute, 30, DATEADD(hour, 5, c.CHARGE_DATE)) AS DATE), 'MM-yyyy') AS DatePart,
		0 AS HAL_IB_FG_AB,
		0 AS HAL_IB_FG_TC,
		0 AS HAL_IB_MR_AB,
		0 AS HAL_IB_POSM_AB,
		0 AS HAL_IB_DOC_AB,
		0 AS HAL_OB_FG_AB,
		0 AS HAL_OB_FG_TC,
		SUM(c.CHARGE_QTY) AS HAL_OB_MR_AB,
		0 AS HAL_OB_POSM_AB,
		0 AS HAL_OB_DOC_AB,
		0 AS HAL_AB_TOT,
		0 AS Extra_AB,
		0 AS HAL_FG_TC_TOT,
		0 AS Extra_TC		
		
	FROM BILLADMIN.BIC_CHARGE_CODE CHG_CODE
	LEFT JOIN BILLADMIN.BIC_CHARGE c ON CHG_CODE.CHARGE_CODE = c.CHARGE_CODE
	WHERE c.CHARGE_CODE = 'HAL-OB-MR-AB'
	GROUP BY FORMAT(CAST(DATEADD(minute, 30, DATEADD(hour, 5, c.CHARGE_DATE)) AS DATE), 'MM-yyyy')
	
	UNION ALL
	
	SELECT FORMAT(CAST(DATEADD(minute, 30, DATEADD(hour, 5, c.CHARGE_DATE)) AS DATE), 'MM-yyyy') AS DatePart,	
		0 AS HAL_IB_FG_AB,
		0 AS HAL_IB_FG_TC,
		0 AS HAL_IB_MR_AB,
		0 AS HAL_IB_POSM_AB,
		0 AS HAL_IB_DOC_AB,
		0 AS HAL_OB_FG_AB,
		0 AS HAL_OB_FG_TC,
		0 AS HAL_OB_MR_AB,
		SUM(c.CHARGE_QTY) AS HAL_OB_POSM_AB,
		0 AS HAL_OB_DOC_AB,
		0 AS HAL_AB_TOT,
		0 AS Extra_AB,
		0 AS HAL_FG_TC_TOT,
		0 AS Extra_TC		
		
	FROM BILLADMIN.BIC_CHARGE_CODE CHG_CODE
	LEFT JOIN BILLADMIN.BIC_CHARGE c ON CHG_CODE.CHARGE_CODE = c.CHARGE_CODE
	WHERE c.CHARGE_CODE = 'HAL-OB-POSM-AB'
	GROUP BY FORMAT(CAST(DATEADD(minute, 30, DATEADD(hour, 5, c.CHARGE_DATE)) AS DATE), 'MM-yyyy')
	
	UNION ALL
	
	SELECT FORMAT(CAST(DATEADD(minute, 30, DATEADD(hour, 5, c.CHARGE_DATE)) AS DATE), 'MM-yyyy') AS DatePart,
		0 AS HAL_IB_FG_AB,
		0 AS HAL_IB_FG_TC,
		0 AS HAL_IB_MR_AB,
		0 AS HAL_IB_POSM_AB,
		0 AS HAL_IB_DOC_AB,
		0 AS HAL_OB_FG_AB,
		0 AS HAL_OB_FG_TC,
		0 AS HAL_OB_MR_AB,
		0 AS HAL_OB_POSM_AB,
		SUM(c.CHARGE_QTY) AS HAL_OB_DOC_AB,
		0 AS HAL_AB_TOT,
		0 AS Extra_AB,
		0 AS HAL_FG_TC_TOT,
		0 AS Extra_TC
		
		
	FROM BILLADMIN.BIC_CHARGE_CODE CHG_CODE
	LEFT JOIN BILLADMIN.BIC_CHARGE c ON CHG_CODE.CHARGE_CODE = c.CHARGE_CODE
	WHERE c.CHARGE_CODE = 'HAL-OB-DOC-AB'
	GROUP BY FORMAT(CAST(DATEADD(minute, 30, DATEADD(hour, 5, c.CHARGE_DATE)) AS DATE), 'MM-yyyy')
	
	-----------------------------------------------------------------------------------------------------
	UNION ALL
	
	--Storage & Extra
	SELECT
		Extra.DatePart AS DatePart,
		0 AS HAL_IB_FG_AB,
		0 AS HAL_IB_FG_TC,
		0 AS HAL_IB_MR_AB,
		0 AS HAL_IB_POSM_AB,
		0 AS HAL_IB_DOC_AB,
		0 AS HAL_OB_FG_AB,
		0 AS HAL_OB_FG_TC,
		0 AS HAL_OB_MR_AB,
		0 AS HAL_OB_POSM_AB,
		0 AS HAL_OB_DOC_AB,
		SUM(Extra.HAL_OB_FG_AB) + SUM(Extra.HL_FG_AB) + SUM(Extra.HAL_OB_MR_AB) + SUM(Extra.HL_MR) + SUM(Extra.HAL_OB_DOC_AB) + SUM(Extra.HL_DOC) + SUM(Extra.HAL_OB_POSM_AB) + SUM(Extra.HL_POSM) AS HAL_AB_TOT,
		(SUM(Extra.HAL_OB_FG_AB) + SUM(Extra.HL_FG_AB) + SUM(Extra.HAL_OB_MR_AB) + SUM(Extra.HL_MR) + SUM(Extra.HAL_OB_DOC_AB) + SUM(Extra.HL_DOC) + SUM(Extra.HAL_OB_POSM_AB) + SUM(Extra.HL_POSM)) - 650.00 AS Extra_AB,
		SUM(Extra.HAL_OB_FG_TC) + SUM(Extra.HL_FG) AS HAL_FG_TC_TOT,
		(SUM(Extra.HAL_OB_FG_TC) + SUM(Extra.HL_FG)) - 100.00 AS Extra_TC
		
	FROM
	(
		-----------------------------------------------------------------------------------------------------------------------
		SELECT
			FORMAT(CAST(DATEADD(minute, 30, DATEADD(hour, 5, c.CHARGE_DATE)) AS DATE), 'MM-yyyy') AS DatePart,
			CAST(DATEADD(minute, 30, DATEADD(hour, 5, c.CHARGE_DATE)) AS DATE) AS Cal_Date,
			SUM(c.CHARGE_QTY) AS HAL_OB_FG_AB,
			0 AS HL_FG_AB,
			0 AS HAL_OB_MR_AB,
			0 AS HL_MR,
			0 AS HAL_OB_DOC_AB,
			0 AS HL_DOC,
			0 AS HAL_OB_POSM_AB,
			0 AS HL_POSM,
			0 AS HAL_OB_FG_TC,
			0 AS HL_FG
			
		FROM BILLADMIN.BIC_CHARGE_CODE CHG_CODE
		LEFT JOIN BILLADMIN.BIC_CHARGE c ON CHG_CODE.CHARGE_CODE = c.CHARGE_CODE
		WHERE c.CHARGE_CODE = 'HAL-OB-FG-AB'	
		GROUP BY CAST(DATEADD(minute, 30, DATEADD(hour, 5, c.CHARGE_DATE)) AS DATE)

		UNION ALL

		SELECT
			FORMAT(CAST(DATEADD(minute, 30, DATEADD(hour, 5, c.CHARGE_DATE)) AS DATE), 'MM-yyyy') AS DatePart,
			CAST(DATEADD(minute, 30, DATEADD(hour, 5, c.CHARGE_DATE)) AS DATE) AS Cal_Date,
			0 AS HAL_OB_FG_AB,
			SUM(c.CHARGE_QTY) AS HL_FG_AB,
			0 AS HAL_OB_MR_AB,
			0 AS HL_MR,
			0 AS HAL_OB_DOC_AB,
			0 AS HL_DOC,
			0 AS HAL_OB_POSM_AB,
			0 AS HL_POSM,
			0 AS HAL_OB_FG_TC,
			0 AS HL_FG
			
		FROM BILLADMIN.BIC_CHARGE_CODE CHG_CODE
		LEFT JOIN BILLADMIN.BIC_CHARGE c ON CHG_CODE.CHARGE_CODE = c.CHARGE_CODE
		WHERE c.CHARGE_CODE = 'HAL-ST-AB' AND c.ITEM_GROUP = 'HL-FG-AB'
		GROUP BY CAST(DATEADD(minute, 30, DATEADD(hour, 5, c.CHARGE_DATE)) AS DATE)
		-----------------------------------------------------------------------------------------------------------------------
		UNION ALL
		
		SELECT
			FORMAT(CAST(DATEADD(minute, 30, DATEADD(hour, 5, c.CHARGE_DATE)) AS DATE), 'MM-yyyy') AS DatePart,
			CAST(DATEADD(minute, 30, DATEADD(hour, 5, c.CHARGE_DATE)) AS DATE) AS Cal_Date,
			0 AS HAL_OB_FG_AB,
			0 AS HL_FG_AB,
			SUM(c.CHARGE_QTY) AS HAL_OB_MR_AB,
			0 AS HL_MR,
			0 AS HAL_OB_DOC_AB,
			0 AS HL_DOC,
			0 AS HAL_OB_POSM_AB,
			0 AS HL_POSM,
			0 AS HAL_OB_FG_TC,
			0 AS HL_FG

		FROM BILLADMIN.BIC_CHARGE_CODE CHG_CODE
		LEFT JOIN BILLADMIN.BIC_CHARGE c ON CHG_CODE.CHARGE_CODE = c.CHARGE_CODE
		WHERE c.CHARGE_CODE = 'HAL-OB-MR-AB'	
		GROUP BY CAST(DATEADD(minute, 30, DATEADD(hour, 5, c.CHARGE_DATE)) AS DATE)

		UNION ALL

		SELECT
			FORMAT(CAST(DATEADD(minute, 30, DATEADD(hour, 5, c.CHARGE_DATE)) AS DATE), 'MM-yyyy') AS DatePart,
			CAST(DATEADD(minute, 30, DATEADD(hour, 5, c.CHARGE_DATE)) AS DATE) AS Cal_Date,
			0 AS HAL_OB_FG_AB,
			0 AS HL_FG_AB,
			0 AS HAL_OB_MR_AB,
			SUM(c.CHARGE_QTY) AS HL_MR,
			0 AS HAL_OB_DOC_AB,
			0 AS HL_DOC,
			0 AS HAL_OB_POSM_AB,
			0 AS HL_POSM,
			0 AS HAL_OB_FG_TC,
			0 AS HL_FG
			
		FROM BILLADMIN.BIC_CHARGE_CODE CHG_CODE
		LEFT JOIN BILLADMIN.BIC_CHARGE c ON CHG_CODE.CHARGE_CODE = c.CHARGE_CODE
		WHERE c.CHARGE_CODE = 'HAL-ST-AB' AND c.ITEM_GROUP = 'HL-MR'
		GROUP BY CAST(DATEADD(minute, 30, DATEADD(hour, 5, c.CHARGE_DATE)) AS DATE)
		-----------------------------------------------------------------------------------------------------------------------
		UNION ALL
		
		SELECT
			FORMAT(CAST(DATEADD(minute, 30, DATEADD(hour, 5, c.CHARGE_DATE)) AS DATE), 'MM-yyyy') AS DatePart,
			CAST(DATEADD(minute, 30, DATEADD(hour, 5, c.CHARGE_DATE)) AS DATE) AS Cal_Date,
			0 AS HAL_OB_FG_AB,
			0 AS HL_FG_AB,
			0 AS HAL_OB_MR_AB,
			0 AS HL_MR,
			SUM(c.CHARGE_QTY) AS HAL_OB_DOC_AB,
			0 AS HL_DOC,
			0 AS HAL_OB_POSM_AB,
			0 AS HL_POSM,
			0 AS HAL_OB_FG_TC,
			0 AS HL_FG

		FROM BILLADMIN.BIC_CHARGE_CODE CHG_CODE
		LEFT JOIN BILLADMIN.BIC_CHARGE c ON CHG_CODE.CHARGE_CODE = c.CHARGE_CODE
		WHERE c.CHARGE_CODE = 'HAL-OB-DOC-AB'	
		GROUP BY CAST(DATEADD(minute, 30, DATEADD(hour, 5, c.CHARGE_DATE)) AS DATE)

		UNION ALL

		SELECT
			FORMAT(CAST(DATEADD(minute, 30, DATEADD(hour, 5, c.CHARGE_DATE)) AS DATE), 'MM-yyyy') AS DatePart,
			CAST(DATEADD(minute, 30, DATEADD(hour, 5, c.CHARGE_DATE)) AS DATE) AS Cal_Date,
			0 AS HAL_OB_FG_AB,
			0 AS HL_FG_AB,
			0 AS HAL_OB_MR_AB,
			0 AS HL_MR,
			0 AS HAL_OB_DOC_AB,
			SUM(c.CHARGE_QTY) AS HL_DOC,
			0 AS HAL_OB_POSM_AB,
			0 AS HL_POSM,
			0 AS HAL_OB_FG_TC,
			0 AS HL_FG
			
		FROM BILLADMIN.BIC_CHARGE_CODE CHG_CODE
		LEFT JOIN BILLADMIN.BIC_CHARGE c ON CHG_CODE.CHARGE_CODE = c.CHARGE_CODE
		WHERE c.CHARGE_CODE = 'HAL-ST-AB' AND c.ITEM_GROUP = 'HL-DOC'
		GROUP BY CAST(DATEADD(minute, 30, DATEADD(hour, 5, c.CHARGE_DATE)) AS DATE)
		-----------------------------------------------------------------------------------------------------------------------
		UNION ALL
		
		SELECT
			FORMAT(CAST(DATEADD(minute, 30, DATEADD(hour, 5, c.CHARGE_DATE)) AS DATE), 'MM-yyyy') AS DatePart,
			CAST(DATEADD(minute, 30, DATEADD(hour, 5, c.CHARGE_DATE)) AS DATE) AS Cal_Date,
			0 AS HAL_OB_FG_AB,
			0 AS HL_FG_AB,
			0 AS HAL_OB_MR_AB,
			0 AS HL_MR,
			0 AS HAL_OB_DOC_AB,
			0 AS HL_DOC,
			0 AS HAL_OB_POSM_AB,
			0 AS HL_POSM,
			SUM(c.CHARGE_QTY) AS HAL_OB_FG_TC,
			0 AS HL_FG

		FROM BILLADMIN.BIC_CHARGE_CODE CHG_CODE
		LEFT JOIN BILLADMIN.BIC_CHARGE c ON CHG_CODE.CHARGE_CODE = c.CHARGE_CODE
		WHERE c.CHARGE_CODE = 'HAL-OB-FG-TC'	
		GROUP BY CAST(DATEADD(minute, 30, DATEADD(hour, 5, c.CHARGE_DATE)) AS DATE)

		UNION ALL

		SELECT
			FORMAT(CAST(DATEADD(minute, 30, DATEADD(hour, 5, c.CHARGE_DATE)) AS DATE), 'MM-yyyy') AS DatePart,
			CAST(DATEADD(minute, 30, DATEADD(hour, 5, c.CHARGE_DATE)) AS DATE) AS Cal_Date,
			0 AS HAL_OB_FG_AB,
			0 AS HL_FG_AB,
			0 AS HAL_OB_MR_AB,
			0 AS HL_MR,
			0 AS HAL_OB_DOC_AB,
			0 AS HL_DOC,
			0 AS HAL_OB_POSM_AB,
			0 AS HL_POSM,
			0 AS HAL_OB_FG_TC,
			SUM(c.CHARGE_QTY) AS HL_FG
			
		FROM BILLADMIN.BIC_CHARGE_CODE CHG_CODE
		LEFT JOIN BILLADMIN.BIC_CHARGE c ON CHG_CODE.CHARGE_CODE = c.CHARGE_CODE
		WHERE c.CHARGE_CODE = 'HAL-ST-TC' AND c.ITEM_GROUP = 'HL-FG'
		GROUP BY CAST(DATEADD(minute, 30, DATEADD(hour, 5, c.CHARGE_DATE)) AS DATE)
		-----------------------------------------------------------------------------------------------------------------------
	)Extra
	GROUP BY
		Extra.DatePart
	-----------------------------------------------------------------------------------------------------
	
)Summary
GROUP BY Summary.DatePart
