SELECT 
  Inbound.DatePart,
	Inbound.Cal_Date,
	Inbound.HAL_IB_FG_AB,
	Inbound.HAL_IB_FG_TC,
	Inbound.HAL_IB_MR_AB,
	Inbound.HAL_IB_POSM_AB,
	Inbound.HAL_IB_SR_AB,
	Inbound.HAL_IB_SR_TC,
	Inbound.HAL_IB_DOC_AB
FROM (
	SELECT FORMAT(CAST(DATEADD(minute, 30, DATEADD(hour, 5, c.CHARGE_DATE)) AS DATE), 'MM-yyyy') AS DatePart,
		CAST(DATEADD(minute, 30, DATEADD(hour, 5, c.CHARGE_DATE)) AS DATE) AS Cal_Date,
		SUM(c.CHARGE_QTY) AS HAL_IB_FG_AB,
		0 AS HAL_IB_FG_TC,
		0 AS HAL_IB_MR_AB,
		0 AS HAL_IB_POSM_AB,
		0 AS HAL_IB_SR_AB,
		0 AS HAL_IB_SR_TC,
		0 AS HAL_IB_DOC_AB
	FROM BILLADMIN.BIC_CHARGE_CODE CHG_CODE
	LEFT JOIN BILLADMIN.BIC_CHARGE c ON CHG_CODE.CHARGE_CODE = c.CHARGE_CODE
	WHERE c.CHARGE_CODE = 'HAL-IB-FG-AB'
	GROUP BY CAST(DATEADD(minute, 30, DATEADD(hour, 5, c.CHARGE_DATE)) AS DATE)
	
	UNION ALL
	
	SELECT FORMAT(CAST(DATEADD(minute, 30, DATEADD(hour, 5, c.CHARGE_DATE)) AS DATE), 'MM-yyyy') AS DatePart,
		CAST(DATEADD(minute, 30, DATEADD(hour, 5, c.CHARGE_DATE)) AS DATE) AS Cal_Date,
		0 AS HAL_IB_FG_AB,
		SUM(c.CHARGE_QTY) AS HAL_IB_FG_TC,
		0 AS HAL_IB_MR_AB,
		0 AS HAL_IB_POSM_AB,
		0 AS HAL_IB_SR_AB,
		0 AS HAL_IB_SR_TC,
		0 AS HAL_IB_DOC_AB
	FROM BILLADMIN.BIC_CHARGE_CODE CHG_CODE
	LEFT JOIN BILLADMIN.BIC_CHARGE c ON CHG_CODE.CHARGE_CODE = c.CHARGE_CODE
	WHERE c.CHARGE_CODE = 'HAL-IB-FG-TC'
	GROUP BY CAST(DATEADD(minute, 30, DATEADD(hour, 5, c.CHARGE_DATE)) AS DATE)
	
	UNION ALL
	
	SELECT FORMAT(CAST(DATEADD(minute, 30, DATEADD(hour, 5, c.CHARGE_DATE)) AS DATE), 'MM-yyyy') AS DatePart,
		CAST(DATEADD(minute, 30, DATEADD(hour, 5, c.CHARGE_DATE)) AS DATE) AS Cal_Date,
		0 AS HAL_IB_FG_AB,
		0 AS HAL_IB_FG_TC,
		SUM(c.CHARGE_QTY) AS HAL_IB_MR_AB,
		0 AS HAL_IB_POSM_AB,
		0 AS HAL_IB_SR_AB,
		0 AS HAL_IB_SR_TC,
		0 AS HAL_IB_DOC_AB
	FROM BILLADMIN.BIC_CHARGE_CODE CHG_CODE
	LEFT JOIN BILLADMIN.BIC_CHARGE c ON CHG_CODE.CHARGE_CODE = c.CHARGE_CODE
	WHERE c.CHARGE_CODE = 'HAL-IB-MR-AB'
	GROUP BY CAST(DATEADD(minute, 30, DATEADD(hour, 5, c.CHARGE_DATE)) AS DATE)
	
	UNION ALL
	
	SELECT FORMAT(CAST(DATEADD(minute, 30, DATEADD(hour, 5, c.CHARGE_DATE)) AS DATE), 'MM-yyyy') AS DatePart,
		CAST(DATEADD(minute, 30, DATEADD(hour, 5, c.CHARGE_DATE)) AS DATE) AS Cal_Date,
		0 AS HAL_IB_FG_AB,
		0 AS HAL_IB_FG_TC,
		0 AS HAL_IB_MR_AB,
		SUM(c.CHARGE_QTY) AS HAL_IB_POSM_AB,
		0 AS HAL_IB_SR_AB,
		0 AS HAL_IB_SR_TC,
		0 AS HAL_IB_DOC_AB
	FROM BILLADMIN.BIC_CHARGE_CODE CHG_CODE
	LEFT JOIN BILLADMIN.BIC_CHARGE c ON CHG_CODE.CHARGE_CODE = c.CHARGE_CODE
	WHERE c.CHARGE_CODE = 'HAL-IB-POSM-AB'
	GROUP BY CAST(DATEADD(minute, 30, DATEADD(hour, 5, c.CHARGE_DATE)) AS DATE)
	
	UNION ALL
	
	SELECT FORMAT(CAST(DATEADD(minute, 30, DATEADD(hour, 5, c.CHARGE_DATE)) AS DATE), 'MM-yyyy') AS DatePart,
		CAST(DATEADD(minute, 30, DATEADD(hour, 5, c.CHARGE_DATE)) AS DATE) AS Cal_Date,
		0 AS HAL_IB_FG_AB,
		0 AS HAL_IB_FG_TC,
		0 AS HAL_IB_MR_AB,
		0 AS HAL_IB_POSM_AB,
		SUM(c.CHARGE_QTY) AS HAL_IB_SR_AB,
		0 AS HAL_IB_SR_TC,
		0 AS HAL_IB_DOC_AB
	FROM BILLADMIN.BIC_CHARGE_CODE CHG_CODE
	LEFT JOIN BILLADMIN.BIC_CHARGE c ON CHG_CODE.CHARGE_CODE = c.CHARGE_CODE
	WHERE c.CHARGE_CODE = 'HAL-IB-SR-AB'
	GROUP BY CAST(DATEADD(minute, 30, DATEADD(hour, 5, c.CHARGE_DATE)) AS DATE)
	
	UNION ALL
	
	SELECT FORMAT(CAST(DATEADD(minute, 30, DATEADD(hour, 5, c.CHARGE_DATE)) AS DATE), 'MM-yyyy') AS DatePart,
		CAST(DATEADD(minute, 30, DATEADD(hour, 5, c.CHARGE_DATE)) AS DATE) AS Cal_Date,
		0 AS HAL_IB_FG_AB,
		0 AS HAL_IB_FG_TC,
		0 AS HAL_IB_MR_AB,
		0 AS HAL_IB_POSM_AB,
		0 AS HAL_IB_SR_AB,
		SUM(c.CHARGE_QTY) AS HAL_IB_SR_TC,
		0 AS HAL_IB_DOC_AB
	FROM BILLADMIN.BIC_CHARGE_CODE CHG_CODE
	LEFT JOIN BILLADMIN.BIC_CHARGE c ON CHG_CODE.CHARGE_CODE = c.CHARGE_CODE
	WHERE c.CHARGE_CODE = 'HAL-IB-SR-TC'
	GROUP BY CAST(DATEADD(minute, 30, DATEADD(hour, 5, c.CHARGE_DATE)) AS DATE)
	
	UNION ALL
	
	SELECT FORMAT(CAST(DATEADD(minute, 30, DATEADD(hour, 5, c.CHARGE_DATE)) AS DATE), 'MM-yyyy') AS DatePart,
		CAST(DATEADD(minute, 30, DATEADD(hour, 5, c.CHARGE_DATE)) AS DATE) AS Cal_Date,
		0 AS HAL_IB_FG_AB,
		0 AS HAL_IB_FG_TC,
		0 AS HAL_IB_MR_AB,
		0 AS HAL_IB_POSM_AB,
		0 AS HAL_IB_SR_AB,
		0 AS HAL_IB_SR_TC,
		SUM(c.CHARGE_QTY) AS HAL_IB_DOC_AB
	FROM BILLADMIN.BIC_CHARGE_CODE CHG_CODE
	LEFT JOIN BILLADMIN.BIC_CHARGE c ON CHG_CODE.CHARGE_CODE = c.CHARGE_CODE
	WHERE c.CHARGE_CODE = 'HAL-IB-DOC-AB'
	GROUP BY CAST(DATEADD(minute, 30, DATEADD(hour, 5, c.CHARGE_DATE)) AS DATE)
	) Inbound
