SELECT
	1 'No',
	'Minimum Commitment for Singer Normal Operation' 'Description',
	FORMAT(DATEADD(minute, 30, DATEADD(hour, 5, c.CHARGE_DATE)), 'MM-yyyy') 'DatePart',
	YEAR(DATEADD(minute, 30, DATEADD(hour, 5, c.CHARGE_DATE))) 'Year',
	SUM(c.CHARGE_AMT) 'Value'
	--0 'Value'
FROM BILLADMIN.BIC_CHARGE c
INNER JOIN BILLADMIN.BIC_CHARGE_CODE CHG_CODE 
ON c.CHARGE_CODE = CHG_CODE.CHARGE_CODE
WHERE c.CHARGE_CODE = 'SIN-N-Fixed'
AND c.DELETE_FLAG = 0
GROUP BY 
	FORMAT(DATEADD(minute, 30, DATEADD(hour, 5, c.CHARGE_DATE)), 'MM-yyyy'),
	YEAR(DATEADD(minute, 30, DATEADD(hour, 5, c.CHARGE_DATE)))

UNION

SELECT
	2 'No',
	'Additional Handling - Inbound (CBM)' 'Description',
    FORMAT(DATEADD(minute, 30, DATEADD(hour, 5, c.CHARGE_DATE)), 'MM-yyyy') 'DatePart',
    YEAR(DATEADD(minute, 30, DATEADD(hour, 5, c.CHARGE_DATE))) 'Year',
	--((SUM(c.CHARGE_QTY))/1000000)- 12750 'Value'
	CASE 
		WHEN SUM(c.CHARGE_QTY) > 12750000000 THEN (SUM(c.CHARGE_QTY) / 1000000) - 12750 
		ELSE 0 
	END  'Value'
FROM BILLADMIN.BIC_CHARGE c
INNER JOIN BILLADMIN.BIC_CHARGE_CODE CHG_CODE 
ON c.CHARGE_CODE = CHG_CODE.CHARGE_CODE
WHERE c.CHARGE_CODE = 'SIN-N-INBHN'
AND c.DELETE_FLAG = 0
GROUP BY 
	FORMAT(DATEADD(minute, 30, DATEADD(hour, 5, c.CHARGE_DATE)), 'MM-yyyy'),
	YEAR(DATEADD(minute, 30, DATEADD(hour, 5, c.CHARGE_DATE)))

UNION

SELECT
	3 'No',
	'Additional Handling - Outbound (CBM)' 'Description',
    FORMAT(DATEADD(minute, 30, DATEADD(hour, 5, c.CHARGE_DATE)), 'MM-yyyy') 'DatePart',
    YEAR(DATEADD(minute, 30, DATEADD(hour, 5, c.CHARGE_DATE))) 'Year',
	--((SUM(c.CHARGE_QTY))/1000000)- 12750 'Value'
	CASE 
		WHEN SUM(c.CHARGE_QTY) > 12750000000 THEN (SUM(c.CHARGE_QTY) / 1000000) - 12750 
		ELSE 0 
	END 'Value'
FROM BILLADMIN.BIC_CHARGE c
INNER JOIN BILLADMIN.BIC_CHARGE_CODE CHG_CODE 
ON c.CHARGE_CODE = CHG_CODE.CHARGE_CODE
WHERE c.CHARGE_CODE = 'SIN-N-OUTHN'
AND c.DELETE_FLAG = 0
GROUP BY 
	FORMAT(DATEADD(minute, 30, DATEADD(hour, 5, c.CHARGE_DATE)), 'MM-yyyy'),
	YEAR(DATEADD(minute, 30, DATEADD(hour, 5, c.CHARGE_DATE)))

UNION

SELECT
    4 'No',
    'Additional Storage (CBM)' 'Description',
    FORMAT(DATEADD(minute, 30, DATEADD(hour, 5, d.CHARGE_DATE)), 'MM-yyyy') AS "DatePart",
    YEAR(DATEADD(minute, 30, DATEADD(hour, 5, d.CHARGE_DATE))) AS "Year",
    SUM(d.Excess) 'Value'
FROM (
    
    SELECT 
        c.CHARGE_DATE,
        SUM(c.CHARGE_QTY) / 1000000 'DailyTotal',
        CASE 
            WHEN (SUM(c.CHARGE_QTY) / 1000000) > 23000 
            THEN (SUM(c.CHARGE_QTY) / 1000000) - 23000 
            ELSE 0 
        END AS Excess
    FROM BILLADMIN.BIC_CHARGE c
    WHERE c.CHARGE_CODE IN ('SIN-N-ST', 'SIN-N-OUTHN')
	AND c.DELETE_FLAG = 0
    GROUP BY c.CHARGE_DATE
) d
GROUP BY 
    FORMAT(DATEADD(minute, 30, DATEADD(hour, 5, d.CHARGE_DATE)), 'MM-yyyy'),
    YEAR(DATEADD(minute, 30, DATEADD(hour, 5, d.CHARGE_DATE)))

UNION

SELECT
	5 'No',
	'Normal OT Unloading' 'Description',
    FORMAT(DATEADD(minute, 30, DATEADD(hour, 5, c.CHARGE_DATE)), 'MM-yyyy') 'DatePart',
    YEAR(DATEADD(minute, 30, DATEADD(hour, 5, c.CHARGE_DATE))) 'Year',
	((SUM(c.CHARGE_QTY))/1000000) 'Value'
FROM BILLADMIN.BIC_CHARGE c
INNER JOIN BILLADMIN.BIC_CHARGE_CODE CHG_CODE 
ON c.CHARGE_CODE = CHG_CODE.CHARGE_CODE
WHERE c.CHARGE_CODE = 'SIN-N-OT-NU'
AND c.DELETE_FLAG = 0
GROUP BY 
	FORMAT(DATEADD(minute, 30, DATEADD(hour, 5, c.CHARGE_DATE)), 'MM-yyyy'),
	YEAR(DATEADD(minute, 30, DATEADD(hour, 5, c.CHARGE_DATE)))
	
UNION

SELECT
	6 'No',
	'Normal OT Loading' 'Description',
    FORMAT(DATEADD(minute, 30, DATEADD(hour, 5, c.CHARGE_DATE)), 'MM-yyyy') 'DatePart',
    YEAR(DATEADD(minute, 30, DATEADD(hour, 5, c.CHARGE_DATE))) 'Year',
	((SUM(c.CHARGE_QTY))/1000000) 'Value'
FROM BILLADMIN.BIC_CHARGE c
INNER JOIN BILLADMIN.BIC_CHARGE_CODE CHG_CODE 
ON c.CHARGE_CODE = CHG_CODE.CHARGE_CODE
WHERE c.CHARGE_CODE = 'SIN-N-OT-NL'
AND c.DELETE_FLAG = 0
GROUP BY 
	FORMAT(DATEADD(minute, 30, DATEADD(hour, 5, c.CHARGE_DATE)), 'MM-yyyy'),
	YEAR(DATEADD(minute, 30, DATEADD(hour, 5, c.CHARGE_DATE)))

UNION

SELECT
	7 'No',
	'Double OT Unloading' 'Description',
    FORMAT(DATEADD(minute, 30, DATEADD(hour, 5, c.CHARGE_DATE)), 'MM-yyyy') 'DatePart',
    YEAR(DATEADD(minute, 30, DATEADD(hour, 5, c.CHARGE_DATE))) 'Year',
	((SUM(c.CHARGE_QTY))/1000000) 'Value'
FROM BILLADMIN.BIC_CHARGE c
INNER JOIN BILLADMIN.BIC_CHARGE_CODE CHG_CODE 
ON c.CHARGE_CODE = CHG_CODE.CHARGE_CODE
WHERE c.CHARGE_CODE = 'SIN-N-OT-DU'
AND c.DELETE_FLAG = 0
GROUP BY 
	FORMAT(DATEADD(minute, 30, DATEADD(hour, 5, c.CHARGE_DATE)), 'MM-yyyy'),
	YEAR(DATEADD(minute, 30, DATEADD(hour, 5, c.CHARGE_DATE)))
	
UNION

SELECT
	8 'No',
	'Double OT Loading' 'Description',
    FORMAT(DATEADD(minute, 30, DATEADD(hour, 5, c.CHARGE_DATE)), 'MM-yyyy') 'DatePart',
    YEAR(DATEADD(minute, 30, DATEADD(hour, 5, c.CHARGE_DATE))) 'Year',
	((SUM(c.CHARGE_QTY))/1000000) 'Value'
FROM BILLADMIN.BIC_CHARGE c
INNER JOIN BILLADMIN.BIC_CHARGE_CODE CHG_CODE 
ON c.CHARGE_CODE = CHG_CODE.CHARGE_CODE
WHERE c.CHARGE_CODE = 'SIN-N-OT-DL'
AND c.DELETE_FLAG = 0
GROUP BY 
	FORMAT(DATEADD(minute, 30, DATEADD(hour, 5, c.CHARGE_DATE)), 'MM-yyyy'),
	YEAR(DATEADD(minute, 30, DATEADD(hour, 5, c.CHARGE_DATE)))

UNION	

SELECT
	9 'No',
	'Container Unloading  40ft_Local' 'Description',
    FORMAT(DATEADD(minute, 30, DATEADD(hour, 5, c.CHARGE_DATE)), 'MM-yyyy') 'DatePart',
    YEAR(DATEADD(minute, 30, DATEADD(hour, 5, c.CHARGE_DATE))) 'Year',
	SUM(c.CHARGE_QTY) 'Value'
FROM BILLADMIN.BIC_CHARGE c
INNER JOIN BILLADMIN.BIC_CHARGE_CODE CHG_CODE 
ON c.CHARGE_CODE = CHG_CODE.CHARGE_CODE
WHERE c.CHARGE_CODE = 'SIN-N-CUL-40FT'
AND c.DELETE_FLAG = 0
GROUP BY 
	FORMAT(DATEADD(minute, 30, DATEADD(hour, 5, c.CHARGE_DATE)), 'MM-yyyy'),
	YEAR(DATEADD(minute, 30, DATEADD(hour, 5, c.CHARGE_DATE)))

UNION
	
SELECT
	10 'No',
	'Container Unloading  20ft_Local' 'Description',
    FORMAT(DATEADD(minute, 30, DATEADD(hour, 5, c.CHARGE_DATE)), 'MM-yyyy') 'DatePart',
    YEAR(DATEADD(minute, 30, DATEADD(hour, 5, c.CHARGE_DATE))) 'Year',
	SUM(c.CHARGE_QTY) 'Value'
FROM BILLADMIN.BIC_CHARGE c
INNER JOIN BILLADMIN.BIC_CHARGE_CODE CHG_CODE 
ON c.CHARGE_CODE = CHG_CODE.CHARGE_CODE
WHERE c.CHARGE_CODE = 'SIN-N-CUL-20FT'
AND c.DELETE_FLAG = 0
GROUP BY 
	FORMAT(DATEADD(minute, 30, DATEADD(hour, 5, c.CHARGE_DATE)), 'MM-yyyy'),
	YEAR(DATEADD(minute, 30, DATEADD(hour, 5, c.CHARGE_DATE)))

UNION

SELECT
	11 'No',
	'Container Unloading  LCL_Local' 'Description',
    FORMAT(DATEADD(minute, 30, DATEADD(hour, 5, c.CHARGE_DATE)), 'MM-yyyy') 'DatePart',
    YEAR(DATEADD(minute, 30, DATEADD(hour, 5, c.CHARGE_DATE))) 'Year',
	SUM(c.CHARGE_QTY) 'Value'
FROM BILLADMIN.BIC_CHARGE c
INNER JOIN BILLADMIN.BIC_CHARGE_CODE CHG_CODE 
ON c.CHARGE_CODE = CHG_CODE.CHARGE_CODE
WHERE c.CHARGE_CODE = 'SIN-N-CUL-LCL'
AND c.DELETE_FLAG = 0
GROUP BY 
	FORMAT(DATEADD(minute, 30, DATEADD(hour, 5, c.CHARGE_DATE)), 'MM-yyyy'),
	YEAR(DATEADD(minute, 30, DATEADD(hour, 5, c.CHARGE_DATE)))

UNION

SELECT
	9 'No',
	'Container Unloading  40ft_Import' 'Description',
    FORMAT(DATEADD(minute, 30, DATEADD(hour, 5, c.CHARGE_DATE)), 'MM-yyyy') 'DatePart',
    YEAR(DATEADD(minute, 30, DATEADD(hour, 5, c.CHARGE_DATE))) 'Year',
	SUM(c.CHARGE_QTY) 'Value'
FROM BILLADMIN.BIC_CHARGE c
INNER JOIN BILLADMIN.BIC_CHARGE_CODE CHG_CODE 
ON c.CHARGE_CODE = CHG_CODE.CHARGE_CODE
WHERE c.CHARGE_CODE = 'SIN-N-CUI-40FT'
AND c.DELETE_FLAG = 0
GROUP BY 
	FORMAT(DATEADD(minute, 30, DATEADD(hour, 5, c.CHARGE_DATE)), 'MM-yyyy'),
	YEAR(DATEADD(minute, 30, DATEADD(hour, 5, c.CHARGE_DATE)))
	
UNION

	
SELECT
	10 'No',
	'Container Unloading  20ft_Import' 'Description',
    FORMAT(DATEADD(minute, 30, DATEADD(hour, 5, c.CHARGE_DATE)), 'MM-yyyy') 'DatePart',
    YEAR(DATEADD(minute, 30, DATEADD(hour, 5, c.CHARGE_DATE))) 'Year',
	SUM(c.CHARGE_QTY) 'Value'
FROM BILLADMIN.BIC_CHARGE c
INNER JOIN BILLADMIN.BIC_CHARGE_CODE CHG_CODE 
ON c.CHARGE_CODE = CHG_CODE.CHARGE_CODE
WHERE c.CHARGE_CODE = 'SIN-N-CUI-20FT'
AND c.DELETE_FLAG = 0
GROUP BY 
	FORMAT(DATEADD(minute, 30, DATEADD(hour, 5, c.CHARGE_DATE)), 'MM-yyyy'),
	YEAR(DATEADD(minute, 30, DATEADD(hour, 5, c.CHARGE_DATE)))

UNION


SELECT
	11 'No',
	'Container Unloading  LCL_Import' 'Description',
    FORMAT(DATEADD(minute, 30, DATEADD(hour, 5, c.CHARGE_DATE)), 'MM-yyyy') 'DatePart',
    YEAR(DATEADD(minute, 30, DATEADD(hour, 5, c.CHARGE_DATE))) 'Year',
	SUM(c.CHARGE_QTY) 'Value'
FROM BILLADMIN.BIC_CHARGE c
INNER JOIN BILLADMIN.BIC_CHARGE_CODE CHG_CODE 
ON c.CHARGE_CODE = CHG_CODE.CHARGE_CODE
WHERE c.CHARGE_CODE = 'SIN-N-CUI-LCL'
AND c.DELETE_FLAG = 0
GROUP BY 
	FORMAT(DATEADD(minute, 30, DATEADD(hour, 5, c.CHARGE_DATE)), 'MM-yyyy'),
	YEAR(DATEADD(minute, 30, DATEADD(hour, 5, c.CHARGE_DATE)))

UNION


SELECT
	12 'No',
	'Night_Meal' 'Description',
    FORMAT(DATEADD(minute, 30, DATEADD(hour, 5, c.CHARGE_DATE)), 'MM-yyyy') 'DatePart',
    YEAR(DATEADD(minute, 30, DATEADD(hour, 5, c.CHARGE_DATE))) 'Year',
	((SUM(c.CHARGE_QTY))/1000000) 'Value'
FROM BILLADMIN.BIC_CHARGE c
INNER JOIN BILLADMIN.BIC_CHARGE_CODE CHG_CODE 
ON c.CHARGE_CODE = CHG_CODE.CHARGE_CODE
WHERE c.CHARGE_CODE = 'SIN-N-MEAL'
AND c.DELETE_FLAG = 0
GROUP BY 
	FORMAT(DATEADD(minute, 30, DATEADD(hour, 5, c.CHARGE_DATE)), 'MM-yyyy'),
	YEAR(DATEADD(minute, 30, DATEADD(hour, 5, c.CHARGE_DATE)))

UNION


SELECT
	13 'No',
	'Night_Transportation' 'Description',
    FORMAT(DATEADD(minute, 30, DATEADD(hour, 5, c.CHARGE_DATE)), 'MM-yyyy') 'DatePart',
    YEAR(DATEADD(minute, 30, DATEADD(hour, 5, c.CHARGE_DATE))) 'Year',
	((SUM(c.CHARGE_QTY))/1000000) 'Value'
FROM BILLADMIN.BIC_CHARGE c
INNER JOIN BILLADMIN.BIC_CHARGE_CODE CHG_CODE 
ON c.CHARGE_CODE = CHG_CODE.CHARGE_CODE
WHERE c.CHARGE_CODE = 'SIN-N-TRAN'
AND c.DELETE_FLAG = 0
GROUP BY 
	FORMAT(DATEADD(minute, 30, DATEADD(hour, 5, c.CHARGE_DATE)), 'MM-yyyy'),
	YEAR(DATEADD(minute, 30, DATEADD(hour, 5, c.CHARGE_DATE)))

UNION


SELECT
	14 'No',
	'VAS Operations' 'Description',
    FORMAT(DATEADD(minute, 30, DATEADD(hour, 5, c.CHARGE_DATE)), 'MM-yyyy') 'DatePart',
    YEAR(DATEADD(minute, 30, DATEADD(hour, 5, c.CHARGE_DATE))) 'Year',
	((SUM(c.CHARGE_QTY))/1000000) 'Value'
FROM BILLADMIN.BIC_CHARGE c
INNER JOIN BILLADMIN.BIC_CHARGE_CODE CHG_CODE 
ON c.CHARGE_CODE = CHG_CODE.CHARGE_CODE
WHERE c.CHARGE_CODE = 'SIN-N-VAS'
AND c.DELETE_FLAG = 0
GROUP BY 
	FORMAT(DATEADD(minute, 30, DATEADD(hour, 5, c.CHARGE_DATE)), 'MM-yyyy'),
	YEAR(DATEADD(minute, 30, DATEADD(hour, 5, c.CHARGE_DATE)))
